services:
  modsec-apache:
    container_name: modsec-apache-alpine
    image: owasp/modsecurity-crs:apache-alpine
    environment:
      SERVERNAME: modsec-apache-alpine
      BACKEND: "http://192.168.1.10:3000"
      PORT: "80"
      MODSEC_AUDIT_ENGINE: On
      BLOCKING_PARANOIA: 2
      ERRORLOG: "/var/log/modsec_error.log"
      ACCESSLOG: "/var/log/modsec_access.log"
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG_PARTS: ABDEFHIJZ
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.log"
      MODSEC_TMP_DIR: "/tmp"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      COMBINED_FILE_SIZES: "65535"
    volumes:
      - "/var/log/:/var/log/"
    ports:
      - "80:80"

  juiceshop_prod:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
